---
title: "Actividad 2 - Ejercicios de Analisis de Datos"
author: "Maximo"
date: "2026-09-03"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Ejercicio 1: Variacion porcentual

```{r ejercicio1}
ventas_inicial <- 200000
ventas_final <- 260000

costos_inicial <- 120000
costos_final <- 150000

# a) Variacion porcentual de ventas
var_ventas <- ((ventas_final - ventas_inicial) / ventas_inicial) * 100

# b) Variacion porcentual de costos
var_costos <- ((costos_final - costos_inicial) / costos_inicial) * 100

# c) Utilidad inicial y final
utilidad_inicial <- ventas_inicial - costos_inicial
utilidad_final <- ventas_final - costos_final

# Variacion porcentual de utilidad
var_utilidad <- ((utilidad_final - utilidad_inicial) / utilidad_inicial) * 100

cat("Variacion de ventas:", round(var_ventas, 2), "%\n")
cat("Variacion de costos:", round(var_costos, 2), "%\n")
cat("Utilidad inicial: $", utilidad_inicial, "\n")
cat("Utilidad final: $", utilidad_final, "\n")
cat("Variacion de utilidad:", round(var_utilidad, 2), "%\n")
```

## Ejercicio 2: Promedio ponderado

```{r ejercicio2}
hombres_total <- 400
hombres_tasa <- 0.35

mujeres_total <- 600
mujeres_tasa <- 0.45

hombres_aprueban <- hombres_total * hombres_tasa
mujeres_aprueban <- mujeres_total * mujeres_tasa

total_aprueban <- hombres_aprueban + mujeres_aprueban
total_personas <- hombres_total + mujeres_total

tasa_global <- (total_aprueban / total_personas) * 100
promedio_simple <- ((hombres_tasa + mujeres_tasa) / 2) * 100

cat("Hombres que aprueban:", hombres_aprueban, "\n")
cat("Mujeres que aprueban:", mujeres_aprueban, "\n")
cat("Tasa global (ponderada):", round(tasa_global, 2), "%\n")
cat("Promedio simple (incorrecto):", round(promedio_simple, 2), "%\n")
```

## Ejercicio 3: Paradoja de Simpson

```{r ejercicio3}
# Hospital A
A_bajo_casos <- 100
A_bajo_exitos <- 98
A_alto_casos <- 100
A_alto_exitos <- 60

# Hospital B
B_bajo_casos <- 300
B_bajo_exitos <- 288
B_alto_casos <- 100
B_alto_exitos <- 55

A_bajo_tasa <- (A_bajo_exitos / A_bajo_casos) * 100
A_alto_tasa <- (A_alto_exitos / A_alto_casos) * 100
A_global <- ((A_bajo_exitos + A_alto_exitos) / (A_bajo_casos + A_alto_casos)) * 100

B_bajo_tasa <- (B_bajo_exitos / B_bajo_casos) * 100
B_alto_tasa <- (B_alto_exitos / B_alto_casos) * 100
B_global <- ((B_bajo_exitos + B_alto_exitos) / (B_bajo_casos + B_alto_casos)) * 100

cat("Hospital A - Bajo riesgo:", round(A_bajo_tasa, 2), "%\n")
cat("Hospital A - Alto riesgo:", round(A_alto_tasa, 2), "%\n")
cat("Hospital A - Global:", round(A_global, 2), "%\n")
cat("Hospital B - Bajo riesgo:", round(B_bajo_tasa, 2), "%\n")
cat("Hospital B - Alto riesgo:", round(B_alto_tasa, 2), "%\n")
cat("Hospital B - Global:", round(B_global, 2), "%\n")
```

## Ejercicio 4: Valor esperado

```{r ejercicio4}
precio_poliza <- 50
prob_siniestro <- 0.02
pago_siniestro <- 2000

pago_esperado <- prob_siniestro * pago_siniestro
ganancia_esperada <- precio_poliza - pago_esperado

cat("Pago esperado por siniestro: $", pago_esperado, "\n")
cat("Ganancia esperada por poliza: $", ganancia_esperada, "\n")
```

## Ejercicio 5: Modelo lineal

```{r ejercicio5}
gasto_fijo <- 180
pendiente <- 0.25

aumento_ingreso <- 1000
aumento_gasto <- pendiente * aumento_ingreso

ingreso_ejemplo <- 2000
gasto_estimado <- gasto_fijo + pendiente * ingreso_ejemplo

porcentaje_gasto <- (gasto_estimado / ingreso_ejemplo) * 100

cat("Gasto fijo mensual: $", gasto_fijo, "\n")
cat("Gasto marginal (por cada peso extra): $", pendiente, "\n")
cat("Si el ingreso sube $", aumento_ingreso, ", el gasto sube: $", aumento_gasto, "\n")
cat("Con ingreso de $", ingreso_ejemplo, ", gasto estimado: $", gasto_estimado, "\n")
cat("Ese gasto representa el", round(porcentaje_gasto, 2), "% del ingreso\n")
```